import type { Candidate } from './types';

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    rank: 1,
    name: 'Julie Monroe',
    title: 'Nutrition Consultant',
    location: 'Los Angeles',
    email: 'julie.monroe@email.com',
    phone: '3868683442',
    overallScore: 87,
    signal: 'strong',
    scoreBreakdown: {
      skills: 94,
      experience: 78,
      keywords: 71,
      education: 100,
    },
    skillMatch: {
      matched: ['Python', 'FastAPI', 'PostgreSQL', 'REST APIs', 'Docker', 'Git', 'Redis', 'CI/CD', 'Linux', 'SQL', 'Agile', 'Unit Testing'],
      missing: ['Kubernetes', 'Terraform'],
      extra: ['TPN protocols', 'WIC Program', 'Clinical nutrition', 'USDA'],
    },
    knockoutChecks: [
      { label: 'Min experience (3yr)', passed: true, detail: '4.5yr found' },
      { label: 'Required degree', passed: true, detail: "Master's" },
      { label: 'Must-have skills', passed: true, detail: 'all present' },
    ],
    experience: [
      {
        id: 'e1',
        role: 'Nutritional Consultant',
        company: 'WIC',
        startDate: 'Jan 2021',
        endDate: 'Present',
        durationYears: 3.5,
      },
      {
        id: 'e2',
        role: 'Nutritional Consultant',
        company: 'DaVita',
        startDate: 'Jan 2016',
        endDate: 'Nov 2019',
        durationYears: 3.9,
      },
    ],
    education: [
      {
        id: 'ed1',
        degree: 'Master of Science',
        field: 'Dietary Education',
        institution: 'Golden Valley University',
        yearRange: '2020-2021',
      },
    ],
    flags: [
      { type: 'warning', message: 'Missing: Kubernetes, Terraform' },
      { type: 'info', message: 'Most recent role is part-time' },
    ],
    topSkills: ['Python', 'FastAPI', '4.5yr'],
    totalYears: 4.5,
    status: 'under-review',
    note: '',
  },
  {
    id: '2',
    rank: 2,
    name: 'Raj Patel',
    title: 'Senior Software Engineer',
    location: 'San Francisco',
    email: 'raj.patel@email.com',
    phone: '4155551234',
    overallScore: 81,
    signal: 'strong',
    scoreBreakdown: {
      skills: 88,
      experience: 85,
      keywords: 72,
      education: 80,
    },
    skillMatch: {
      matched: ['Python', 'Django', 'PostgreSQL', 'REST APIs', 'Docker', 'Git', 'AWS', 'Redis', 'CI/CD', 'Linux'],
      missing: ['FastAPI', 'Kubernetes'],
      extra: ['GraphQL', 'Terraform', 'MongoDB'],
    },
    knockoutChecks: [
      { label: 'Min experience (3yr)', passed: true, detail: '6yr found' },
      { label: 'Required degree', passed: true, detail: "Bachelor's" },
      { label: 'Must-have skills', passed: true, detail: 'all present' },
    ],
    experience: [
      {
        id: 'e3',
        role: 'Senior Software Engineer',
        company: 'TechCorp',
        startDate: 'Mar 2020',
        endDate: 'Present',
        durationYears: 4.0,
      },
      {
        id: 'e4',
        role: 'Software Engineer',
        company: 'StartupXYZ',
        startDate: 'Jun 2018',
        endDate: 'Feb 2020',
        durationYears: 2.0,
      },
    ],
    education: [
      {
        id: 'ed2',
        degree: 'Bachelor of Science',
        field: 'Computer Science',
        institution: 'UC Berkeley',
        yearRange: '2014-2018',
      },
    ],
    flags: [],
    topSkills: ['Python', 'Django', '6yr'],
    totalYears: 6,
    status: 'under-review',
    note: '',
  },
  {
    id: '3',
    rank: 3,
    name: 'Amy Chen',
    title: 'Backend Developer',
    location: 'Seattle',
    email: 'amy.chen@email.com',
    phone: '2065559876',
    overallScore: 74,
    signal: 'good',
    scoreBreakdown: {
      skills: 76,
      experience: 65,
      keywords: 80,
      education: 75,
    },
    skillMatch: {
      matched: ['Python', 'PostgreSQL', 'REST APIs', 'Git', 'Docker', 'Linux', 'SQL', 'Agile'],
      missing: ['FastAPI', 'Kubernetes', 'Redis'],
      extra: ['Flask', 'React', 'TypeScript'],
    },
    knockoutChecks: [
      { label: 'Min experience (3yr)', passed: true, detail: '3yr found' },
      { label: 'Required degree', passed: true, detail: "Bachelor's" },
      { label: 'Must-have skills', passed: true, detail: 'all present' },
    ],
    experience: [
      {
        id: 'e5',
        role: 'Backend Developer',
        company: 'WebAgency',
        startDate: 'Aug 2021',
        endDate: 'Present',
        durationYears: 3.0,
      },
    ],
    education: [
      {
        id: 'ed3',
        degree: 'Bachelor of Science',
        field: 'Software Engineering',
        institution: 'University of Washington',
        yearRange: '2017-2021',
      },
    ],
    flags: [
      { type: 'info', message: 'Part-time flag' },
    ],
    topSkills: ['Python', '3yr', 'Part-time flag'],
    totalYears: 3,
    status: 'under-review',
    note: '',
  },
  {
    id: '4',
    rank: 4,
    name: 'Mark Davis',
    title: 'Junior Developer',
    location: 'Austin',
    email: 'mark.davis@email.com',
    phone: '5125554321',
    overallScore: 61,
    signal: 'fair',
    scoreBreakdown: {
      skills: 55,
      experience: 60,
      keywords: 68,
      education: 70,
    },
    skillMatch: {
      matched: ['Python', 'Git', 'Docker', 'Linux', 'SQL', 'Agile'],
      missing: ['PostgreSQL', 'REST APIs', 'FastAPI', 'Kubernetes'],
      extra: ['Java', 'Spring Boot', 'MySQL'],
    },
    knockoutChecks: [
      { label: 'Min experience (3yr)', passed: true, detail: '3.5yr found' },
      { label: 'Required degree', passed: true, detail: "Bachelor's" },
      { label: 'Must-have skills', passed: false, detail: 'missing PostgreSQL, REST APIs' },
    ],
    experience: [
      {
        id: 'e6',
        role: 'Junior Developer',
        company: 'DevShop',
        startDate: 'Jan 2021',
        endDate: 'Present',
        durationYears: 3.5,
      },
    ],
    education: [
      {
        id: 'ed4',
        degree: 'Bachelor of Arts',
        field: 'Information Technology',
        institution: 'UT Austin',
        yearRange: '2017-2021',
      },
    ],
    flags: [
      { type: 'warning', message: 'Missing: PostgreSQL, REST APIs' },
    ],
    topSkills: ['Python', 'Docker', '3.5yr'],
    totalYears: 3.5,
    status: 'under-review',
    note: '',
  },
  {
    id: '5',
    rank: 5,
    name: 'Sam Wright',
    title: 'Marketing Analyst',
    location: 'Chicago',
    email: 'sam.wright@email.com',
    phone: '3125550000',
    overallScore: 0,
    signal: 'knockout',
    scoreBreakdown: {
      skills: 5,
      experience: 0,
      keywords: 10,
      education: 20,
    },
    skillMatch: {
      matched: ['SQL'],
      missing: ['Python', 'PostgreSQL', 'REST APIs', 'FastAPI', 'Docker', 'Git', 'Kubernetes'],
      extra: ['Excel', 'Tableau', 'Google Analytics', 'HubSpot'],
    },
    knockoutChecks: [
      { label: 'Min experience (3yr)', passed: false, detail: '0yr relevant found' },
      { label: 'Required degree', passed: true, detail: "Bachelor's" },
      { label: 'Must-have skills', passed: false, detail: 'missing Python, 3yr exp' },
    ],
    experience: [
      {
        id: 'e7',
        role: 'Marketing Analyst',
        company: 'AdCo',
        startDate: 'May 2019',
        endDate: 'Present',
        durationYears: 5.0,
      },
    ],
    education: [
      {
        id: 'ed5',
        degree: 'Bachelor of Science',
        field: 'Marketing',
        institution: 'DePaul University',
        yearRange: '2015-2019',
      },
    ],
    flags: [
      { type: 'warning', message: 'Missing required: Python, 3yr exp' },
    ],
    topSkills: ['SQL', '0yr relevant'],
    totalYears: 0,
    status: 'under-review',
    note: '',
  },
];
